// ============================================================================
// DEV-ONLY SAMPLE DATA — clearly marked, never committed from prod.
// Used ONLY when the backend returns zero trips, so local dev / a fresh
// install renders something before any real data exists. Nothing in this file
// is ever written to the backend.
// ============================================================================

import type { Booking, Expense, Trip } from './types'

export const SEED_TRIP: Trip = {
  id: 'seed-trip-tokyo-kyoto',
  name: 'Japan: Tokyo → Kyoto',
  destination: 'Tokyo & Kyoto, Japan',
  destination_tz: 'Asia/Tokyo',
  home_tz: 'America/Los_Angeles',
  start_date: '2026-10-10',
  end_date: '2026-10-20',
  notes: 'Sample trip (dev only). Add a real trip from the Calendar tab to replace it.',
  created_at: new Date().toISOString(),
}

export const SEED_BOOKINGS: Booking[] = [
  {
    id: 'seed-flight-lax-hnd',
    trip_id: SEED_TRIP.id,
    kind: 'flight',
    category: 'flight',
    title: 'DL 45 · Los Angeles → Tokyo Haneda',
    airline: 'Delta',
    flight_number: 'DL 45',
    origin: 'LAX',
    destination: 'HND',
    depart_at: '2026-10-10T11:00:00-07:00',
    arrive_at: '2026-10-11T14:55:00+09:00',
    points_cost: 95000,
    point_currency: 'Amex MR',
    cash_paid: 112.4,
    cash_currency: 'USD',
    booking_account: 'Daniel · SkyMiles',
    confirmation_number: 'H7XK2P',
    ticket_number: '0061234567890',
    seat: '32A',
    checked_bags: 2,
    change_cancel_deadline: '2026-09-25',
    cents_per_point: 1.8,
    hotel_name: null,
    address: null,
    check_in: null,
    check_out: null,
    room_type: null,
    free_night_certs: null,
    resort_fees: null,
    cancellation_deadline: null,
    location: null,
    maps_url: null,
    start_at: null,
    end_at: null,
    cost: null,
    notes: 'Sample (dev only)',
    created_at: new Date().toISOString(),
  },
  {
    id: 'seed-hotel-tokyo',
    trip_id: SEED_TRIP.id,
    kind: 'hotel',
    category: 'hotel',
    title: 'Park Hotel Tokyo',
    airline: null,
    flight_number: null,
    origin: null,
    destination: null,
    depart_at: null,
    arrive_at: null,
    points_cost: null,
    point_currency: null,
    cash_paid: null,
    cash_currency: 'USD',
    booking_account: 'Sara · Marriott Bonvoy',
    confirmation_number: 'M12345678',
    ticket_number: null,
    seat: null,
    checked_bags: null,
    change_cancel_deadline: null,
    cents_per_point: null,
    hotel_name: 'Park Hotel Tokyo',
    address: '1-7-1 Shiodome, Minato City',
    check_in: '2026-10-11',
    check_out: '2026-10-15',
    room_type: 'Deluxe King, city view',
    free_night_certs: 0,
    resort_fees: 0,
    cancellation_deadline: '2026-10-08',
    location: null,
    maps_url: null,
    start_at: null,
    end_at: null,
    cost: null,
    notes: 'Sample (dev only)',
    created_at: new Date().toISOString(),
  },
  {
    id: 'seed-event-sushi',
    trip_id: SEED_TRIP.id,
    kind: 'event',
    category: 'food',
    title: 'Omakase at Sushi no Midori',
    airline: null,
    flight_number: null,
    origin: null,
    destination: null,
    depart_at: null,
    arrive_at: null,
    points_cost: null,
    point_currency: null,
    cash_paid: null,
    cash_currency: 'USD',
    booking_account: null,
    confirmation_number: null,
    ticket_number: null,
    seat: null,
    checked_bags: null,
    change_cancel_deadline: null,
    cents_per_point: null,
    hotel_name: null,
    address: null,
    check_in: null,
    check_out: null,
    room_type: null,
    free_night_certs: null,
    resort_fees: null,
    cancellation_deadline: null,
    location: 'Shibuya, Tokyo',
    maps_url: null,
    start_at: '2026-10-12T18:30:00+09:00',
    end_at: '2026-10-12T20:30:00+09:00',
    cost: 90,
    notes: 'Sample (dev only)',
    created_at: new Date().toISOString(),
  },
  {
    id: 'seed-event-kyoto',
    trip_id: SEED_TRIP.id,
    kind: 'event',
    category: 'fun',
    title: 'Fushimi Inari hike',
    airline: null,
    flight_number: null,
    origin: null,
    destination: null,
    depart_at: null,
    arrive_at: null,
    points_cost: null,
    point_currency: null,
    cash_paid: null,
    cash_currency: 'USD',
    booking_account: null,
    confirmation_number: null,
    ticket_number: null,
    seat: null,
    checked_bags: null,
    change_cancel_deadline: null,
    cents_per_point: null,
    hotel_name: null,
    address: null,
    check_in: null,
    check_out: null,
    room_type: null,
    free_night_certs: null,
    resort_fees: null,
    cancellation_deadline: null,
    location: 'Fushimi, Kyoto',
    maps_url: null,
    start_at: '2026-10-17T09:00:00+09:00',
    end_at: '2026-10-17T13:00:00+09:00',
    cost: 0,
    notes: 'Sample (dev only)',
    created_at: new Date().toISOString(),
  },
]

export const SEED_BUDGET = { total_budget: 3000, currency: 'USD' }

export const SEED_EXPENSES: Expense[] = [
  {
    id: 'seed-expense-1',
    trip_id: SEED_TRIP.id,
    date: '2026-10-11',
    amount: 45.2,
    currency: 'USD',
    category: 'food',
    note: 'Ramen in Asakusa',
    source: 'manual',
    created_at: new Date().toISOString(),
  },
  {
    id: 'seed-expense-2',
    trip_id: SEED_TRIP.id,
    date: '2026-10-12',
    amount: 120,
    currency: 'USD',
    category: 'fun',
    note: 'teamLab tickets',
    source: 'manual',
    created_at: new Date().toISOString(),
  },
]
